automation: !include automations.yaml
binary_sensor: !include_dir_merge_list binary_sensors/
light: !include lights.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/