- platform: mqtt
  name: "Garden Pro4 Input 0"
  unique_id: binary_sensor.garden_pro4_input_0
  value_template: "{{ value_json.state }}"
  payload_on: "True"
  payload_off: "False"
  state_topic: shellies/garden-pro4/status/input:0

- platform: mqtt
  name: "Garden Pro4 Input 1"
  unique_id: binary_sensor.garden_pro4_input_1
  value_template: "{{ value_json.state }}"
  payload_on: "True"
  payload_off: "False"
  state_topic: shellies/garden-pro4/status/input:1

- platform: mqtt
  name: "Garden Pro4 Input 2"
  unique_id: binary_sensor.garden_pro4_input_2
  value_template: "{{ value_json.state }}"
  payload_on: "True"
  payload_off: "False"
  state_topic: shellies/garden-pro4/status/input:2

- platform: mqtt
  name: "Garden Pro4 Input 3"
  unique_id: binary_sensor.garden_pro4_input_3
  value_template: "{{ value_json.state }}"
  payload_on: "True"
  payload_off: "False"
  state_topic: shellies/garden-pro4/status/input:3

- platform: mqtt  
  name: "Garden Pro4 Firmware Update"
  unique_id: binary_sensor.garden_pro4_firmware_update
  device_class: update
  state_topic: homeassistant/shelly/garden-pro4/rpc
  value_template: >
    {%- if value_json.result.sys.available_updates.stable is defined %}
    ON
    {%- else %}
    OFF
    {%- endif %}
  json_attributes_topic: homeassistant/shelly/garden-pro4/rpc
  json_attributes_template: >
    {%- if value_json.result.sys.available_updates.stable is defined %}
    {{ value_json.result.sys.available_updates.stable | tojson }}
    {%- endif %}
